services:
  cypress:
    container_name: cypress
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    volumes:
      - ./cypress/test:/e2e/cypress/test
      - ./cypress.config.js:/e2e/cypress.config.js
    working_dir: /e2e
    environment:
      - DISPLAY=:99
      - XVFB_WHD=1920x1080x24
      - ELECTRON_ENABLE_LOGGING=1
    command: ["sh", "-c", "Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset -nolisten tcp & sleep 3 && tail -f /dev/null"]
